alias(
    name = "Shuffleboard",
    actual = "@shuffleboard//app",
)

alias(
    name = "Pathweaver",
    actual = "@pathweaver//:pathweaver",
)

alias(
    name = "SysId",
    actual = "@sysid//src/main/native:sysid",
)

alias(
    name = "SysId-Drivetrain",
    actual = "@sysid//base_projects/Drivetrain:gui",
)
